/** Pagefind's UI bundle is generated by the postbuild step and loaded at runtime. */
interface PagefindUiInstance {
  triggerSearch(term: string): void;
}

interface Window {
  PagefindUI?: new (options: Record<string, unknown>) => PagefindUiInstance;
}
