/** Injected by `astro.config.mjs` via a Vite define, not by dotenv. */
interface ImportMetaEnv {
  /** Short SHA of the commit this build came from; "dev" outside a checkout. */
  readonly COMMIT_SHA: string;
}

/** Pagefind's UI bundle is generated by the postbuild step and loaded at runtime. */
interface PagefindUiInstance {
  triggerSearch(term: string): void;
}

interface Window {
  PagefindUI?: new (options: Record<string, unknown>) => PagefindUiInstance;
}
